apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: debug
  name: debug
spec:
  containers:
  - image: k8s.gcr.io/nginx-slim:0.8
    name: debug
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
