apiVersion: v1
kind: Service
metadata:
  labels:
    app: dogorcat
  name: rabbitmq-admin-svc
spec:
  ports:
  - name: admin
    port: 15672
    targetPort: 15672
    nodePort: 30000
  selector:
    app: dogorcat
    type: queue
  type: NodePort

