apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-13T11:31:24Z"
  labels:
    app: dogorcat
    type: queue
  name: rabbitmq-admin-svc
  namespace: default
  resourceVersion: "55067"
  selfLink: /api/v1/namespaces/default/services/rabbitmq-admin-svc
  uid: f9043289-3e63-4869-9f62-15bcec7048a5
spec:
  clusterIP: 10.108.210.135
  externalTrafficPolicy: Cluster
  ports:
  - name: port-admin
    nodePort: 31553
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: dogorcat
    type: queue
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
