apiVersion: v1
kind: Service
metadata:
  labels:
    app: dogorcat
    type: queue
  name: rabbitmq-svc
  namespace: default
spec:
  ports:
  - name: port-queue
    port: 5672
  selector:
    app: dogorcat
    type: queue
  type: ClusterIP
