apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mq
  name: mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mq
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
