apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dogorcat
    type: worker
  name: go-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dogorcat
      type: worker
  template:
    metadata:
      labels:
        app: dogorcat
        type: worker
    spec:
      containers:
      - image: go-worker:1.0
        name: go-worker
        env:
          - name: RABBIT_URL
            valueFrom:
              configMapKeyRef:
                 name: config-rabbitmq
                 key: url
          - name: RABBIT_USER
            valueFrom:
              secretKeyRef:
                 name: secret-rabbitmq
                 key: username
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: secret-rabbitmq
                 key: password
          - name: RABBIT_QUEUE_NAME
            valueFrom:
              configMapKeyRef:
                 name: config-rabbitmq
                 key: queueName
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                 name: config-mysql
                 key: host
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                 name: config-mysql
                 key: port
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                 name: secret-mysql
                 key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: secret-mysql
                 key: password
          - name: MYSQL_DBNAME
            valueFrom:
              configMapKeyRef:
                 name: config-mysql
                 key: dbName

